{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project }}
  source:
    {{ if eq .type "helm" }}
    repoURL: {{ .repoUrl }}
    chart: {{ .chartName }}
    targetRevision: {{ .chartVersion }}
    helm:
      releaseName: {{ .name }}
      valueFiles:
      - {{ .valuesFilePath }}
    {{ end }}
    {{ if eq .type "k8s" }}
    repoURL: {{ .repoUrl }}
    targetRevision: main
    path: ./{{ .project }}/{{ .name }}
    {{ end }}
  destination:
    server: {{ .cluster }}
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
{{- end }}